# For information about what configuration options are available, see
# https://slashdeploy.io/docs"
---
environments:
  production:
    aliases:
      - prod
    continuous_delivery: &cd
      ref: refs/heads/master
      required_contexts:
        - "ci/circleci: test"
        - "ci/circleci: docker_image"
        - "ci/circleci: docker_image_and_vuln_scanning_with_ecr"
  # staging:
  #   aliases:
  #     - stage
  #   continuous_delivery:
  #     !!merge <<: *cd
